package com.example.cs3270a7_trevoregbert.db;
import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity
public class Course {

    // Holds the database ID autoGenerated
    @PrimaryKey(autoGenerate = true)
    private int cid;
    // Holds the database course_number
    private String course_number;
    // Holds the name
    private String name;
    // Holds the course_code
    private String course_code;
    // Holds the start_at
    private String start_at;
    // Holds the end_at
    private String end_at;

    /**
     * Constructor for the Course class
     * @param course_number: The course number of the course
     * @param name: Name of the course
     * @param course_code: The course code of the course
     * @param start_at: The start at of the course
     * @param end_at: The end at of the course
     */
    public Course(String course_number, String name, String course_code, String start_at, String end_at) {
        this.course_number = course_number;
        this.name = name;
        this.course_code = course_code;
        this.start_at = start_at;
        this.end_at = end_at;
    }

    @NonNull
    @Override
    public String toString() {
        return "Course{" +
                "cid=" + cid +
                ", course_number='" + course_number + '\'' +
                ", name='" + name + '\'' +
                ", course_code='" + course_code + '\'' +
                ", start_at='" + start_at + '\'' +
                ", end_at='" + end_at + '\'' +
                '}';
    }

    /**
     * Gets cid
     * @return int the cid of the course
     */
    public int getCid() {
        return cid;
    }

    /**
     * Sets the course cid
     * @param cid: int to set the cid
     */
    public void setCid(int cid) {
        this.cid = cid;
    }

    /**
     * Gets course_number
     * @return string the course number of the course
     */
    public String getCourse_number() {
        return course_number;
    }

    /**
     * Sets course_number
     * @param course_number: string to set course_number
     */
    public void setCourse_number(String course_number) {
        this.course_number = course_number;
    }

    /**
     * Gets name
     * @return string the course number of the course
     */
    public String getName() {
        return name;
    }

    /**
     * Sets name
     * @param name: string to set name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets course_code
     * @return string the course number of the course
     */
    public String getCourse_code() {
        return course_code;
    }

    /**
     * Sets course_code
     * @param course_code: string to set course_code
     */
    public void setCourse_code(String course_code) {
        this.course_code = course_code;
    }

    /**
     * Gets start_at
     * @return string the course number of the course
     */
    public String getStart_at() {
        return start_at;
    }

    /**
     * Sets start_at
     * @param start_at: string to set start_at
     */
    public void setStart_at(String start_at) {
        this.start_at = start_at;
    }

    /**
     * Gets end_at
     * @return string the course number of the course
     */
    public String getEnd_at() {
        return end_at;
    }

    /**
     * Set end_at
     * @param end_at: string to set end_at
     */
    public void setEnd_at(String end_at) {
        this.end_at = end_at;
    }
}

